---
ansible_user: centos
ansible_ssh_private_key_file: keys/servers/centos.pem

#MongoDB
mongodb_user: admin
mongodb_password: Gfq82rDtyC3rZg8t
mongodb_binding: 0.0.0.0

nodejs_version: 14.19.0
nodejs_npm_global_packages:
  - pm2
  - gulp
  - node-gyp

#php
php_version: '7.3'
php_enable_webserver: false
php_webserver_daemon: "nginx"
php_enable_apc: false
php_fpm_pool_user: nginx
php_fpm_pool_group: nginx
php_packages:
  - php
  - php-curl
  - php-gd
  - php-intl
  - php-pear
  - php-imagick
  - php-imap
  - php-mcrypt
  - php-memcache
  - php-recode
  - php-sqlite3
  - php-tidy
  - php-xmlrpc
  - php-xsl
  - php-mbstring
  - php-gettext
  - php-opcache
  - php-apcu
  - php-fpm
  - php-gd
  - php-pecl-zip

#php-fpm
php_enable_php_fpm: true
php_fpm_state: started
php_fpm_enabled_on_boot: true
php_fpm_listen: "127.0.0.1:9000"
php_fpm_listen_allowed_clients: "127.0.0.1"
php_fpm_pm_max_children: 50
php_fpm_pm_start_servers: 5
php_fpm_pm_min_spare_servers: 5
php_fpm_pm_max_spare_servers: 5

#php.ini
php_memory_limit: "128M"
php_max_execution_time: "90"
php_expose_php: "Off"
php_display_errors: "Off"
php_file_uploads: "On"
php_upload_max_filesize: "10M"
php_max_file_uploads: "20"
php_post_max_size: "15M"

#mysql
mysql_root_username: root
mysql_root_password: Gfq82rDtyC3rZg8t
mysql_root_password_update: false
mysql_enabled_on_startup: true
mysql_port: "3306"
mysql_bind_address: "0.0.0.0"
mysql_databases:
  - name: blog
    encoding: utf8
    collation: utf8_unicode_ci
mysql_users:
  - name: blog
    host: "localhost"
    password: Gfq82rDtyC3rZg8t
    priv: "blog.*:ALL"
  - name: mpazo
    host: "%"
    password: Gfq82rDtyC3rZg8t
    priv: "*.*:ALL"
