---
- name: Install yum packages
  yum:
    name: "{{ yum_packages }}"
    state: present

- name: Copy redis file redis.conf
  template:
    src: redis.conf.j2
    dest: /etc/redis.conf

- name: Restart redis
  service:
    name: redis
    state: restarted

- name: Enable redis for start on init SO
  service:
    name: redis
    enabled: yes
