---
- name: Create login user
  user:
    name: "{{ user }}"
    state: present
    createhome: yes

- name: Set authorized key took from file
  authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ item }}"
  with_file:
    - "{{ playbook_dir }}/keys/sudoers/{{ user }}.pem"

- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s

- name: Add sudoers sudoers to wheel group
  user:
    name: "{{ user }}"
    groups: wheel
    append: yes
