---
- name: Install MongoDB
  hosts: servers
  become: true
  vars:
    ansible_user: centos
    ansible_ssh_private_key_file: keys/servers/centos.pem
    ansible_python_interpreter: /usr/local/bin/python3.7
  roles:
    - role: geerlingguy.epel
    - role: mongodb
      vars:
        - mongodb_user: admin
        - mongodb_password: 3KPEDzQgkm2z3cwV
        - mongodb_binding: 0.0.0.0
    - role: sudoers
      vars:
        - user: mpazo
