---
- name: Install Redis
  hosts: redis
  become: true
  vars:
    ansible_user: centos
    ansible_ssh_private_key_file: keys/servers/centos.pem
  roles:
    - role: redis
      vars:
        - redis_password: 3KPEDzQgkm2z3cwV

