---

- name: Check if Supervisor is running
  command: systemctl status supervisord
  ignore_errors: yes
  changed_when: false
  register: service_supervisor_status

- debug: msg="{{ service_supervisor_status.stdout_lines }}"

- name: Install supervisor with python
  become: true
  shell: /usr/local/bin/pip3.7 install supervisor
  when: service_supervisor_status.rc != 0

- name: Add user supervisor
  user:
    name: supervisor
    shell: /sbin/nologin
    append: yes
    state: present

- name: Creates home directory
  file:
    path: "{{ supervisor_home }}"
    state: directory
    owner: supervisor
    group: supervisor
  when: service_supervisor_status.rc != 0

- name: Creates config directory
  file:
    path: "{{ supervisor_config_path }}"
    state: directory
    owner: supervisor
    group: supervisor
  when: service_supervisor_status.rc != 0

- name: Creates log directory
  file:
    path: "{{ supervisor_log_path }}"
    state: directory
    owner: supervisor
    group: supervisor
  when: service_supervisor_status.rc != 0

- name: Copying main config file
  template:
    src: supervisord.conf.j2
    dest: "{{ supervisor_home }}/supervisord.conf"

- name: Copying config file {{ item }}
  template:
    src: "{{ supervisor_config_prefix }}{{ item }}"
    dest: "{{ supervisor_config_path }}/{{ item }}"
  with_items: "{{ supervisor_config_files }}"

- name: Ensure supervisor directory permissions
  file:
    path: "{{ supervisor_home }}"
    state: directory
    recurse: yes
    mode: 0664
    owner: supervisor
    group: supervisor

- name: Creating supervisor service
  template:
    src: supervisord.service.j2
    dest: /etc/systemd/system/supervisord.service

- name: Restart daemon
  systemd:
    state: restarted
    daemon_reload: yes
    name: crond

- name: Start supervisor service
  systemd:
    name: supervisord
    state: restarted

- name: Enable supervisor service
  systemd:
    name: supervisord
    enabled: yes
