---
- name: Install yum packages
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ yum_packages }}"

- name: Install required packages for install php
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ php_required_packages }}"

- name: Install required rpm for install php
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ php_required_rpms }}"

- name: Add repository
  yum_repository:
    name: remi
    description: REMI YUM repo
    baseurl: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    gpgcheck: no

- name: Disable php 5.4
  shell: yum-config-manager --disable remi-php54

- name: Enable php 7.3
  shell: yum-config-manager --enable remi-php73

- name: Disable remi
  shell: yum-config-manager --disable remi
